First_commit
NET16-Homeworks/Homework_EfCore pull request #1
Opened 2022-11-09 07:57 UTC by BFipe

Ну вроде готово, коль вьюшки для добавления всех-всех нужны, то сделаю, коль нет, то нет

2022-11-13 12:07 UTC, im-kborovik requested changes

2022-11-13 12:07 UTC, im-kborovik commented on Homework_EfCore/Homework_EfCore/Database/DBService.cs
> +    public static class DBService
Так, нет. Сделай его плз обычным классом. Забываем о статических классах-сервисах. Это очень важные классы, которые содержат сложную бизнес логику. Статическими могут быть хэлперы какие-нибудь, которые содержат минималистичную логику (типа 2+2).

2022-11-13 12:07 UTC, im-kborovik commented on Homework_EfCore/Homework_EfCore/Database/DBService.cs
> +        public static DBInfo info;
`Action<string>` ?))

2022-11-13 12:07 UTC, im-kborovik commented on Homework_EfCore/Homework_EfCore/Database/DBService.cs
> +        private static async Task<Author> _ReturnAuthorByName(string lastName)
что за подчёркивание впереди названия метода?

2022-11-13 12:07 UTC, im-kborovik commented on Homework_EfCore/Homework_EfCore/Database/DBService.cs
> +                }
так я запутался в этих проверках.
я предлагаю это сильно упростить:
1. проверяй user и book на null в самом начале, если null, то сообщение и retrun.
2. то же самое с data, будет идти сразу за ними
3. если код прошёл эти три проверки, то делаем то, что у тебя в data != null блоке.

2022-11-13 12:07 UTC, im-kborovik commented on Homework_EfCore/Homework_EfCore/Database/DBService.cs
> +                }
Сделай через один запрос без foreach. Для этого используй навигационные поля и проекцию данных

2022-11-13 12:07 UTC, im-kborovik commented on Homework_EfCore/Homework_EfCore/Database/MyDBContext.cs
> +                q => q.HasOne(q => q.User).WithMany(q => q.UserBooks).HasForeignKey(q => q.UserId));
А это ты почему не вынес в UserConfiguration?

2022-11-13 12:07 UTC, im-kborovik commented on Homework_EfCore/Homework_EfCore/Models/Author.cs
> +    public class AuthorConfiguration : IEntityTypeConfiguration<Author>
Вынеси все конфигурации в отдельные файлы.

2022-11-13 16:57 UTC, BFipe commented on Homework_EfCore/Homework_EfCore/Database/DBService.cs
> +        private static async Task<Author> _ReturnAuthorByName(string lastName)
Для приваток, нас так раньше учили оформлять

2022-11-14 07:31 UTC, BFipe commented on Homework_EfCore/Homework_EfCore/Database/DBService.cs
> +        public static DBInfo info;
!!!

2022-11-21 14:40 UTC, im-kborovik approved these changes

2022-11-21 14:40 UTC, closed without merging